### LSTM
***
- LSTM(Long Short Term Memory) is a more enhanced RNN that is used to counteract the exploding/ vanishing gradient problems caused by a vanilla RNN (Recurrent Neural Network)

1. **Notebook Summary:**
- Inner Workings Behind LSTM
- Different Applications of LSTM
    - Stacked LSTM
    - Parallel LSTM
    - Bidirectional LSTM
- PyTorch Example of LSTM

In [1]:
import torch
import torch.nn as nn
import torchinfo
import numpy as np

#### 3. Pytorch 
***
**`nn.LSTM(input_size, hidden_state, num_layers)`**
- `input_size`: the number of expect feature in the input x
- `hidden_size`: the number of features in the hidden state
- `num_layers`: the number of recurrent layers 
    <br></br>
1. `.forward(inputs, hidden_state=torch.zeros(1, hidden_state)))`
- forward has two inputs, the previous activation layer and the input values
- for the previous activation layer, when set to a dimension, create a zero vector of that dimension as its default value
   - inputs: represents the data you want to look through

In [3]:
torch.manual_seed(42)
data = torch.rand(30, 2)

In [6]:
lstm = nn.LSTM(3, 1)
lstm.state_dict()["weight_ih_l0"].shape # [4 x 10, 1]
lstm.state_dict()["weight_hh_l0"].shape # [4 x 10, 10]
lstm.state_dict()['bias_ih_l0'].shape # [4 x 10]
lstm.state_dict()['bias_hh_l0'].shape # [4 x 10]

lstm.forward(torch.Tensor(data))

(tensor([[-0.1820],
         [-0.2777],
         [-0.2803],
         [-0.3054],
         [-0.1888],
         [-0.1919],
         [-0.2007],
         [-0.2140],
         [-0.2003],
         [-0.2898],
         [-0.2943],
         [-0.3001],
         [-0.3193],
         [-0.2736],
         [-0.2303],
         [-0.1745],
         [-0.1956],
         [-0.2829],
         [-0.2583],
         [-0.2460],
         [-0.2307],
         [-0.2346],
         [-0.2078],
         [-0.2126],
         [-0.2049],
         [-0.3162],
         [-0.3306],
         [-0.2495],
         [-0.2343],
         [-0.1874]], grad_fn=<SqueezeBackward1>),
 (tensor([[-0.1874]], grad_fn=<SqueezeBackward1>),
  tensor([[-0.4414]], grad_fn=<SqueezeBackward1>)))

#### 